version: '3'
services:
  notebook:
    container_name: jupyter_notebook
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home
    stdin_open: true
    ports:
      - 8888:8888